import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { createContext, runInContext } from "node:vm";

const root = dirname(fileURLToPath(import.meta.url));
const same = (actual, expected) => assert.equal(JSON.stringify(actual), JSON.stringify(expected));
const loadScript = (handler, configuration) => {
  const calls = [];
  const context = createContext({
    ScriptContext: { configuration: configuration || {} },
    ConnectionApp: { getApiKey: async () => "pat" },
    UrlFetchApp: {
      fetch: async (url, options = {}) => {
        const method = String(options.method || "GET").toUpperCase();
        calls.push({ url, method, payload: options.payload, authorization: options.headers && options.headers.Authorization, contentType: options.headers && options.headers["Content-Type"] });
        const custom = handler ? await handler({ url, method }) : undefined;
        const status = custom && custom.status ? custom.status : method === "DELETE" ? 204 : 200;
        const body = custom && Object.prototype.hasOwnProperty.call(custom, "body") ? custom.body : method === "DELETE" ? "" : { id: "1", kept: true };
        const text = body === "" || body === undefined ? "" : typeof body === "string" ? body : JSON.stringify(body);
        return {
          getResponseCode: () => status,
          getContentText: () => text,
          getHeaders: () => ({ "content-type": custom && custom.contentType ? custom.contentType : "application/json" }),
        };
      },
    },
  });
  runInContext(readFileSync(join(root, "http.js"), "utf8"), context);
  for (const fileName of readdirSync(root).filter((name) => name.endsWith(".js") && name !== "http.js").sort()) {
    runInContext(readFileSync(join(root, fileName), "utf8"), context);
  }
  return { api: context, calls };
};
const origin = "https://api.hubapi.com";

test("object endpoints use HubSpot names and return the response body", async () => {
  const script = loadScript();
  const listed = await script.api.listObjects({ objectType: "contacts", after: "10", archived: false, limit: 2, properties: ["email", "firstname"], propertiesWithHistory: "lifecyclestage", associations: "companies" });
  same(listed, { id: "1", kept: true });
  assert.equal(script.calls[0].method, "GET");
  assert.equal(script.calls[0].url, `${origin}/crm/objects/2026-09/contacts?after=10&archived=false&associations=companies&limit=2&properties=email%2Cfirstname&propertiesWithHistory=lifecyclestage`);
  assert.equal(script.calls[0].authorization, "Bearer pat");
  const read = await script.api.readObject({ objectType: "0-1", objectId: "15", properties: "email", idProperty: "email" });
  same(read, { id: "1", kept: true });
  assert.equal(script.calls[1].url, `${origin}/crm/objects/2026-09/0-1/15?idProperty=email&properties=email`);
  await script.api.createObject({ objectType: "contacts", properties: { email: "a@b.com" }, associations: [{ to: { id: "9" }, types: [{ associationCategory: "HUBSPOT_DEFINED", associationTypeId: 1 }] }] });
  assert.equal(script.calls[2].method, "POST");
  assert.equal(script.calls[2].url, `${origin}/crm/objects/2026-09/contacts`);
  same(JSON.parse(script.calls[2].payload), { properties: { email: "a@b.com" }, associations: [{ to: { id: "9" }, types: [{ associationCategory: "HUBSPOT_DEFINED", associationTypeId: 1 }] }] });
  await script.api.updateObject({ objectType: "contacts", objectId: "15", properties: { firstname: "Ada" }, idProperty: "email" });
  assert.equal(script.calls[3].method, "PATCH");
  assert.equal(script.calls[3].url, `${origin}/crm/objects/2026-09/contacts/15?idProperty=email`);
  same(JSON.parse(script.calls[3].payload), { properties: { firstname: "Ada" } });
  const archived = await script.api.archiveObject({ objectType: "contacts", objectId: "15" });
  same(archived, {});
  assert.equal(script.calls[4].method, "DELETE");
  assert.equal(script.calls[4].payload, undefined);
  await script.api.batchCreateObjects({ objectType: "deals", inputs: [{ properties: { dealname: "A" } }] });
  assert.equal(script.calls[5].url, `${origin}/crm/objects/2026-09/deals/batch/create`);
  await script.api.batchReadObjects({ objectType: "contacts", archived: true, idProperty: "email", properties: ["email"], propertiesWithHistory: ["firstname"], inputs: [{ id: "a@b.com" }] });
  assert.equal(script.calls[6].method, "POST");
  assert.equal(script.calls[6].url, `${origin}/crm/objects/2026-09/contacts/batch/read?archived=true`);
  same(JSON.parse(script.calls[6].payload), { idProperty: "email", properties: ["email"], propertiesWithHistory: ["firstname"], inputs: [{ id: "a@b.com" }] });
  await script.api.batchUpdateObjects({ objectType: "contacts", inputs: [{ id: "15", properties: { firstname: "Ada" }, idProperty: "email" }] });
  same(JSON.parse(script.calls[7].payload), { inputs: [{ id: "15", properties: { firstname: "Ada" }, idProperty: "email" }] });
  await script.api.batchUpsertObjects({ objectType: "contacts", inputs: [{ id: "a@b.com", idProperty: "email", properties: { email: "a@b.com" } }] });
  assert.equal(script.calls[8].url, `${origin}/crm/objects/2026-09/contacts/batch/upsert`);
  same(JSON.parse(script.calls[8].payload), { inputs: [{ id: "a@b.com", idProperty: "email", properties: { email: "a@b.com" } }] });
  await script.api.batchArchiveObjects({ objectType: "contacts", inputs: [{ id: "15" }] });
  assert.equal(script.calls[9].url, `${origin}/crm/objects/2026-09/contacts/batch/archive`);
  await script.api.searchRecords({ objectType: "deals", query: "acme", limit: 10, filterGroups: [{ filters: [{ propertyName: "dealname", operator: "EQ", value: "Acme" }] }] });
  assert.equal(script.calls[10].method, "POST");
  assert.equal(script.calls[10].url, `${origin}/crm/objects/2026-09/deals/search`);
  same(JSON.parse(script.calls[10].payload), { query: "acme", limit: 10, filterGroups: [{ filters: [{ propertyName: "dealname", operator: "EQ", value: "Acme" }] }] });
  assert.equal(script.calls.length, 11);
});

test("association endpoints use HubSpot names and return the response body", async () => {
  const script = loadScript();
  await script.api.listAssociations({ fromObjectType: "contacts", objectId: "15", toObjectType: "companies", after: "2", limit: 5 });
  assert.equal(script.calls[0].url, `${origin}/crm/objects/2026-09/contacts/15/associations/companies?after=2&limit=5`);
  await script.api.associateRecordsLabeled({ objectType: "contacts", objectId: "15", toObjectType: "companies", toObjectId: "9", associationSpec: [{ associationCategory: "USER_DEFINED", associationTypeId: 36 }] });
  assert.equal(script.calls[1].method, "PUT");
  assert.equal(script.calls[1].url, `${origin}/crm/objects/2026-09/contacts/15/associations/companies/9`);
  same(JSON.parse(script.calls[1].payload), [{ associationCategory: "USER_DEFINED", associationTypeId: 36 }]);
  await script.api.associateRecordsDefault({ fromObjectType: "contacts", fromObjectId: "15", toObjectType: "companies", toObjectId: "9" });
  assert.equal(script.calls[2].method, "PUT");
  assert.equal(script.calls[2].payload, undefined);
  assert.equal(script.calls[2].url, `${origin}/crm/objects/2026-09/contacts/15/associations/default/companies/9`);
  const removed = await script.api.removeAssociation({ objectType: "contacts", objectId: "15", toObjectType: "companies", toObjectId: "9" });
  same(removed, {});
  assert.equal(script.calls[3].method, "DELETE");
  const inputs = [{ from: { id: "15" }, to: { id: "9" }, types: [{ associationTypeId: 1 }] }];
  await script.api.batchAssociateRecordsLabeled({ fromObjectType: "contacts", toObjectType: "companies", inputs });
  assert.equal(script.calls[4].url, `${origin}/crm/associations/2026-09/contacts/companies/batch/create`);
  same(JSON.parse(script.calls[4].payload), { inputs });
  await script.api.batchAssociateRecordsDefault({ fromObjectType: "contacts", toObjectType: "companies", inputs: [{ from: { id: "15" }, to: { id: "9" } }] });
  assert.equal(script.calls[5].url, `${origin}/crm/associations/2026-09/contacts/companies/batch/associate/default`);
  await script.api.retrieveAssociations({ fromObjectType: "contacts", toObjectType: "companies", inputs: [{ id: "15", after: "0" }] });
  assert.equal(script.calls[6].url, `${origin}/crm/associations/2026-09/contacts/companies/batch/read`);
  same(JSON.parse(script.calls[6].payload), { inputs: [{ id: "15", after: "0" }] });
  await script.api.deleteAssociationLabels({ fromObjectType: "contacts", toObjectType: "companies", inputs });
  assert.equal(script.calls[7].url, `${origin}/crm/associations/2026-09/contacts/companies/batch/labels/archive`);
  await script.api.removeAssociations({ fromObjectType: "contacts", toObjectType: "companies", inputs: [{ from: { id: "15" }, to: [{ id: "9" }] }] });
  assert.equal(script.calls[8].url, `${origin}/crm/associations/2026-09/contacts/companies/batch/archive`);
  same(JSON.parse(script.calls[8].payload), { inputs: [{ from: { id: "15" }, to: [{ id: "9" }] }] });
  await script.api.reportHighUsage({ userId: "42" });
  assert.equal(script.calls[9].method, "POST");
  assert.equal(script.calls[9].url, `${origin}/crm/associations/2026-09/usage/high-usage-report/42`);
  assert.equal(script.calls[9].payload, undefined);
  await script.api.createAssociationLabel({ fromObjectType: "contacts", toObjectType: "companies", label: "Decision Maker", name: "decision_maker", inverseLabel: "Decision Maker For" });
  assert.equal(script.calls[10].url, `${origin}/crm/associations/2026-09/contacts/companies/labels`);
  same(JSON.parse(script.calls[10].payload), { label: "Decision Maker", name: "decision_maker", inverseLabel: "Decision Maker For" });
  await script.api.retrieveAssociationLabels({ fromObjectType: "contacts", toObjectType: "companies" });
  assert.equal(script.calls[11].method, "GET");
  assert.equal(script.calls[11].url, `${origin}/crm/associations/2026-09/contacts/companies/labels`);
  await script.api.updateAssociationLabel({ fromObjectType: "contacts", toObjectType: "companies", associationTypeId: 36, label: "Buyer", inverseLabel: "Buyer For" });
  assert.equal(script.calls[12].method, "PUT");
  same(JSON.parse(script.calls[12].payload), { associationTypeId: 36, label: "Buyer", inverseLabel: "Buyer For" });
  const deleted = await script.api.deleteAssociationLabel({ fromObjectType: "contacts", toObjectType: "companies", associationTypeId: 36 });
  same(deleted, {});
  assert.equal(script.calls[13].url, `${origin}/crm/associations/2026-09/contacts/companies/labels/36`);
  await script.api.batchCreateLabels({ fromObjectType: "contacts", toObjectType: "companies", inputs: [{ maxToObjectIds: 1, typeId: 36 }] });
  assert.equal(script.calls[14].url, `${origin}/crm/associations/2026-09/definitions/configurations/contacts/companies/batch/create`);
  await script.api.retrieveAssociationLimits({ fromObjectType: "contacts", toObjectType: "companies" });
  assert.equal(script.calls[15].url, `${origin}/crm/associations/2026-09/definitions/configurations/contacts/companies`);
  await script.api.retrieveAllAssociationLimits();
  assert.equal(script.calls[16].url, `${origin}/crm/associations/2026-09/definitions/configurations/all`);
  await script.api.updateAssociationLimits({ fromObjectType: "contacts", toObjectType: "companies", inputs: [{ maxToObjectIds: 2, typeId: 36 }] });
  assert.equal(script.calls[17].url, `${origin}/crm/associations/2026-09/definitions/configurations/contacts/companies/batch/update`);
  await script.api.removeAssociationLimits({ fromObjectType: "contacts", toObjectType: "companies", inputs: [{ category: "USER_DEFINED", typeId: 36 }] });
  assert.equal(script.calls[18].url, `${origin}/crm/associations/2026-09/definitions/configurations/contacts/companies/batch/purge`);
  assert.equal(script.calls.length, 19);
});

test("property endpoints use HubSpot names and return the response body", async () => {
  const script = loadScript();
  await script.api.readAllProperties({ objectType: "contacts", archived: false, dataSensitivity: "non_sensitive", locale: "en", properties: "email" });
  assert.equal(script.calls[0].url, `${origin}/crm/properties/2026-09/contacts?archived=false&dataSensitivity=non_sensitive&locale=en&properties=email`);
  await script.api.readProperty({ objectType: "contacts", propertyName: "email", locale: "en" });
  assert.equal(script.calls[1].url, `${origin}/crm/properties/2026-09/contacts/email?locale=en`);
  await script.api.createProperty({ objectType: "contacts", fieldType: "text", groupName: "contactinformation", label: "Nickname", name: "nickname", type: "string", description: "Short name" });
  assert.equal(script.calls[2].method, "POST");
  same(JSON.parse(script.calls[2].payload), { fieldType: "text", groupName: "contactinformation", label: "Nickname", name: "nickname", type: "string", description: "Short name" });
  await script.api.updateProperty({ objectType: "contacts", propertyName: "nickname", label: "Nick" });
  assert.equal(script.calls[3].method, "PATCH");
  assert.equal(script.calls[3].url, `${origin}/crm/properties/2026-09/contacts/nickname`);
  same(JSON.parse(script.calls[3].payload), { label: "Nick" });
  const archived = await script.api.archiveProperty({ objectType: "contacts", propertyName: "nickname" });
  same(archived, {});
  await script.api.batchCreateProperties({ objectType: "contacts", inputs: [{ groupName: "contactinformation", label: "Nickname", name: "nickname", type: "string", fieldType: "text" }] });
  assert.equal(script.calls[5].url, `${origin}/crm/properties/2026-09/contacts/batch/create`);
  await script.api.batchReadProperties({ objectType: "contacts", locale: "en", archived: true, inputs: [{ name: "email" }] });
  assert.equal(script.calls[6].url, `${origin}/crm/properties/2026-09/contacts/batch/read?locale=en`);
  same(JSON.parse(script.calls[6].payload), { archived: true, inputs: [{ name: "email" }] });
  await script.api.batchArchiveProperties({ objectType: "contacts", inputs: [{ name: "nickname" }] });
  assert.equal(script.calls[7].url, `${origin}/crm/properties/2026-09/contacts/batch/archive`);
  await script.api.createPropertyGroup({ objectType: "contacts", label: "Custom", name: "custom", displayOrder: 2 });
  same(JSON.parse(script.calls[8].payload), { label: "Custom", name: "custom", displayOrder: 2 });
  await script.api.readAllPropertyGroups({ objectType: "contacts", locale: "en" });
  assert.equal(script.calls[9].url, `${origin}/crm/properties/2026-09/contacts/groups?locale=en`);
  await script.api.readPropertyGroup({ objectType: "contacts", groupName: "custom", locale: "en" });
  assert.equal(script.calls[10].url, `${origin}/crm/properties/2026-09/contacts/groups/custom?locale=en`);
  await script.api.updatePropertyGroup({ objectType: "contacts", groupName: "custom", label: "Custom fields", displayOrder: 3 });
  assert.equal(script.calls[11].method, "PATCH");
  same(JSON.parse(script.calls[11].payload), { label: "Custom fields", displayOrder: 3 });
  const group = await script.api.archivePropertyGroup({ objectType: "contacts", groupName: "custom" });
  same(group, {});
  assert.equal(script.calls.length, 13);
});

test("account details and request return HubSpot bodies", async () => {
  const accountBody = { portalId: 42, uiDomain: "app.hubspot.com", timeZone: "UTC" };
  const script = loadScript(({ url }) => {
    if (url.endsWith("/account-info/2026-09/details")) return { body: accountBody };
    if (url.includes("/contacts/99")) return { status: 404, body: { category: "OBJECT_NOT_FOUND", message: "not found", correlationId: "abc" } };
    return undefined;
  });
  const account = await script.api.retrieveAccountDetails();
  same(account, accountBody);
  assert.equal(Object.prototype.hasOwnProperty.call(account, "raw"), false);
  assert.equal(script.calls[0].method, "GET");
  assert.equal(script.calls[0].url, `${origin}/account-info/2026-09/details`);
  const requested = await script.api.request({ path: "crm/objects/2026-09/companies", query: { limit: 1 } });
  same(requested, { id: "1", kept: true });
  assert.equal(script.calls[1].url, `${origin}/crm/objects/2026-09/companies?limit=1`);
  await assert.rejects(() => script.api.readObject({ objectType: "contacts", objectId: "99" }), /HUBSPOT_REQUEST_FAILED \(404 OBJECT_NOT_FOUND abc\): not found/);
  const versioned = loadScript(undefined, { apiVersion: "2026-03" });
  await versioned.api.listObjects({ objectType: "contacts" });
  assert.equal(versioned.calls[0].url, `${origin}/crm/objects/2026-03/contacts`);
  const invalid = loadScript(undefined, { apiVersion: "latest" });
  await assert.rejects(() => invalid.api.listObjects({ objectType: "contacts" }), /HUBSPOT_NOT_CONFIGURED: apiVersion must look like 2026-09/);
  await assert.rejects(() => script.api.listObjects(), /HUBSPOT_INVALID_INPUT: input must be an object/);
  await assert.rejects(() => script.api.createObject({ objectType: "contacts" }), /HUBSPOT_INVALID_INPUT: properties is required/);
  await assert.rejects(() => script.api.batchReadObjects({ objectType: "contacts", inputs: [] }), /HUBSPOT_INVALID_INPUT: inputs is required/);
  await assert.rejects(() => script.api.request({ path: "https://example.com/crm" }), /HUBSPOT_INVALID_INPUT: absolute URLs must stay on https:\/\/api.hubapi.com/);
  assert.equal(script.calls.length, 3);
  const empty = loadScript(() => ({ status: 204, body: "" }));
  same(await empty.api.request({ path: "/crm/owners/2026-09", method: "GET" }), {});
  same(await empty.api.archiveObject({ objectType: "contacts", objectId: "15" }), {});
});

test("a non-JSON success body is the response text", async () => {
  const csv = "email,name\na@b.com,Ada\n";
  const script = loadScript(() => ({ status: 200, body: csv, contentType: "text/csv; charset=utf-8" }));
  const exported = await script.api.request({ path: "/crm/exports/2026-09/export/88" });
  assert.equal(exported, csv);
  assert.equal(typeof exported, "string");
});

test("pipelines, owners, schemas, imports, exports, and property validations use HubSpot names", async () => {
  const script = loadScript();
  await script.api.retrieveAllOwners({ after: "2", archived: false, email: "a@b.com", limit: 10 });
  assert.equal(script.calls[0].url, `${origin}/crm/owners/2026-09?after=2&archived=false&email=a%40b.com&limit=10`);
  await script.api.retrieveOwner({ ownerId: "9", idProperty: "userId", archived: true });
  assert.equal(script.calls[1].url, `${origin}/crm/owners/2026-09/9?archived=true&idProperty=userId`);
  await script.api.createPipeline({ objectType: "deals", displayOrder: 1, label: "Sales", stages: [{ label: "New", displayOrder: 0, metadata: { probability: "0.1" } }] });
  same(JSON.parse(script.calls[2].payload), { displayOrder: 1, label: "Sales", stages: [{ label: "New", displayOrder: 0, metadata: { probability: "0.1" } }] });
  await script.api.retrievePipelines({ objectType: "deals" });
  assert.equal(script.calls[3].url, `${origin}/crm/pipelines/2026-09/deals`);
  await script.api.retrievePipeline({ objectType: "deals", pipelineId: "default" });
  assert.equal(script.calls[4].url, `${origin}/crm/pipelines/2026-09/deals/default`);
  await script.api.retrievePipelineAudit({ objectType: "deals", pipelineId: "default" });
  assert.equal(script.calls[5].url, `${origin}/crm/pipelines/2026-09/deals/default/audit`);
  await script.api.partiallyUpdatePipeline({ objectType: "deals", pipelineId: "default", label: "Revenue", validateReferencesBeforeDelete: true });
  assert.equal(script.calls[6].method, "PATCH");
  assert.equal(script.calls[6].url, `${origin}/crm/pipelines/2026-09/deals/default?validateReferencesBeforeDelete=true`);
  same(JSON.parse(script.calls[6].payload), { label: "Revenue" });
  await script.api.replacePipeline({ objectType: "deals", pipelineId: "default", displayOrder: 1, label: "Sales", stages: [], validateDealStageUsagesBeforeDelete: false });
  assert.equal(script.calls[7].method, "PUT");
  assert.equal(script.calls[7].url, `${origin}/crm/pipelines/2026-09/deals/default?validateDealStageUsagesBeforeDelete=false`);
  same(JSON.parse(script.calls[7].payload), { displayOrder: 1, label: "Sales", stages: [] });
  const removed = await script.api.deletePipeline({ objectType: "deals", pipelineId: "default" });
  same(removed, {});
  assert.equal(script.calls[8].method, "DELETE");
  await script.api.createPipelineStage({ objectType: "deals", pipelineId: "default", displayOrder: 2, label: "Won", metadata: { probability: "1.0" } });
  assert.equal(script.calls[9].url, `${origin}/crm/pipelines/2026-09/deals/default/stages`);
  same(JSON.parse(script.calls[9].payload), { displayOrder: 2, label: "Won", metadata: { probability: "1.0" } });
  await script.api.retrievePipelineStage({ objectType: "deals", pipelineId: "default", stageId: "closedwon" });
  assert.equal(script.calls[10].url, `${origin}/crm/pipelines/2026-09/deals/default/stages/closedwon`);
  await script.api.retrieveStageAudit({ objectType: "deals", pipelineId: "default", stageId: "closedwon" });
  assert.equal(script.calls[11].url, `${origin}/crm/pipelines/2026-09/deals/default/stages/closedwon/audit`);
  await script.api.updatePipelineStage({ objectType: "deals", pipelineId: "default", stageId: "closedwon", displayOrder: 3, label: "Won", metadata: { probability: "1.0" } });
  assert.equal(script.calls[12].method, "PUT");
  await script.api.deletePipelineStage({ objectType: "deals", pipelineId: "default", stageId: "closedwon", validateReferencesBeforeDelete: true });
  assert.equal(script.calls[13].url, `${origin}/crm/pipelines/2026-09/deals/default/stages/closedwon?validateReferencesBeforeDelete=true`);
  const schema = { allowsSensitiveProperties: false, associatedObjects: ["0-1"], labels: { singular: "Car", plural: "Cars" }, name: "car", properties: [{ name: "vin", label: "VIN", type: "string", fieldType: "text" }], requiredProperties: ["vin"], searchableProperties: ["vin"], secondaryDisplayProperties: ["vin"], shouldCreateSameObjectAssociation: false };
  await script.api.createSchema(schema);
  same(JSON.parse(script.calls[14].payload), schema);
  assert.equal(script.calls[14].url, `${origin}/crm-object-schemas/2026-09/schemas`);
  await script.api.retrieveSchema({ objectType: "2-123", includeAssociationDefinitions: true, includePropertyDefinitions: false });
  assert.equal(script.calls[15].url, `${origin}/crm-object-schemas/2026-09/schemas/2-123?includeAssociationDefinitions=true&includePropertyDefinitions=false`);
  await script.api.retrieveSchemas({ archived: false, includeAssociationDefinitions: true });
  assert.equal(script.calls[16].url, `${origin}/crm-object-schemas/2026-09/schemas?archived=false&includeAssociationDefinitions=true`);
  await script.api.updateSchema({ objectType: "2-123", clearDescription: false, labels: { singular: "Auto", plural: "Autos" } });
  same(JSON.parse(script.calls[17].payload), { clearDescription: false, labels: { singular: "Auto", plural: "Autos" } });
  const deleted = await script.api.deleteSchema({ objectType: "2-123", archived: true });
  same(deleted, {});
  assert.equal(script.calls[18].url, `${origin}/crm-object-schemas/2026-09/schemas/2-123?archived=true`);
  await script.api.batchReadSchemas({ includeAssociationDefinitions: true, includeAuditMetadata: false, includePropertyDefinitions: true, inputs: [{ objectType: "2-123" }] });
  same(JSON.parse(script.calls[19].payload), { includeAssociationDefinitions: true, includeAuditMetadata: false, includePropertyDefinitions: true, inputs: [{ objectType: "2-123" }] });
  await script.api.startImport({ files: "email\na@b.com\n", importRequest: "{\"name\":\"People\"}" });
  assert.equal(script.calls[20].method, "POST");
  assert.equal(script.calls[20].url, `${origin}/crm/imports/2026-09`);
  assert.equal(script.calls[20].contentType, "multipart/form-data; boundary=hubspot-form-boundary");
  assert.equal(script.calls[20].payload.includes("name=\"files\""), true);
  assert.equal(script.calls[20].payload.includes("email\na@b.com\n"), true);
  assert.equal(script.calls[20].payload.includes("name=\"importRequest\""), true);
  assert.equal(script.calls[20].payload.includes("{\"name\":\"People\"}"), true);
  await script.api.retrieveImports({ after: "5", limit: 2 });
  assert.equal(script.calls[21].url, `${origin}/crm/imports/2026-09?after=5&limit=2`);
  await script.api.getImport({ importId: "44" });
  assert.equal(script.calls[22].url, `${origin}/crm/imports/2026-09/44`);
  await script.api.cancelImport({ importId: "44" });
  assert.equal(script.calls[23].method, "POST");
  assert.equal(script.calls[23].url, `${origin}/crm/imports/2026-09/44/cancel`);
  assert.equal(script.calls[23].payload, undefined);
  await script.api.retrieveImportErrors({ importId: "44", includeErrorMessage: true, includeRowData: false, limit: 20 });
  assert.equal(script.calls[24].url, `${origin}/crm/imports/2026-09/44/errors?includeErrorMessage=true&includeRowData=false&limit=20`);
  const exportBody = { associatedObjectType: ["COMPANY"], exportInternalValuesOptions: ["NAMES"], exportName: "Deals", exportType: "LIST", format: "CSV", includeLabeledAssociations: false, includePrimaryDisplayPropertyForAssociatedObjects: true, language: "EN", objectProperties: ["dealname"], objectType: "DEAL", overrideAssociatedObjectsPerDefinitionPerRowLimit: false, listId: "12" };
  await script.api.startExport(exportBody);
  assert.equal(script.calls[25].url, `${origin}/crm/exports/2026-09/export/async`);
  same(JSON.parse(script.calls[25].payload), exportBody);
  await script.api.retrieveExportStatus({ taskId: "task-1" });
  assert.equal(script.calls[26].url, `${origin}/crm/exports/2026-09/export/async/tasks/task-1/status`);
  await script.api.retrieveExportDetails({ exportId: "88" });
  assert.equal(script.calls[27].url, `${origin}/crm/exports/2026-09/export/88`);
  await script.api.readAllPropertyValidations({ objectTypeId: "0-1" });
  assert.equal(script.calls[28].url, `${origin}/crm/property-validations/2026-09/0-1`);
  await script.api.readPropertyValidation({ objectTypeId: "0-1", propertyName: "email" });
  assert.equal(script.calls[29].url, `${origin}/crm/property-validations/2026-09/0-1/email`);
  await script.api.retrievePropertyValidationRule({ objectTypeId: "0-1", propertyName: "email", ruleType: "EMAIL" });
  assert.equal(script.calls[30].url, `${origin}/crm/property-validations/2026-09/0-1/email/rule-type/EMAIL`);
  await script.api.updatePropertyValidationRule({ objectTypeId: "0-1", propertyName: "email", ruleType: "FORMAT", ruleArguments: ["EMAIL"], shouldApplyNormalization: true });
  assert.equal(script.calls[31].method, "PUT");
  same(JSON.parse(script.calls[31].payload), { ruleArguments: ["EMAIL"], shouldApplyNormalization: true });
  assert.equal(script.calls.length, 32);
  await assert.rejects(() => script.api.createPipeline({ objectType: "deals", label: "Sales", stages: [] }), /HUBSPOT_INVALID_INPUT: displayOrder is required/);
  await assert.rejects(() => script.api.startImport({ importRequest: "{}" }), /HUBSPOT_INVALID_INPUT: files is required/);
  await assert.rejects(() => script.api.batchReadSchemas({ includeAssociationDefinitions: true, includeAuditMetadata: false, includePropertyDefinitions: true, inputs: [] }), /HUBSPOT_INVALID_INPUT: inputs is required/);
});
